services:
  - type: web
    name: flask-interview-app
    env: python
    plan: free
    python:
      version: 3.12.6
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app